// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineShoppingApp.Data;

#nullable disable

namespace OnlineShoppingApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260227061828_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineShoppingApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 2, 27, 11, 48, 27, 311, DateTimeKind.Local).AddTicks(1149),
                            Description = "Gaming Laptop",
                            DiscountPercentage = 10m,
                            Name = "Laptop",
                            Price = 60000m
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 2, 27, 11, 48, 27, 311, DateTimeKind.Local).AddTicks(1214),
                            Description = "Smart Phone",
                            DiscountPercentage = 5m,
                            Name = "Mobile",
                            Price = 20000m
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 2, 27, 11, 48, 27, 311, DateTimeKind.Local).AddTicks(1216),
                            Description = "Noise Cancelling",
                            DiscountPercentage = 15m,
                            Name = "Headphones",
                            Price = 5000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
